apiVersion: v1
kind: Service
metadata:
  name: javatestservice
spec:
  type: LoadBalancer
  selector:
    app: demo
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}